// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package gwproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type GwError struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwError) Reset()         { *m = GwError{} }
func (m *GwError) String() string { return proto.CompactTextString(m) }
func (*GwError) ProtoMessage()    {}
func (*GwError) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *GwError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwError.Unmarshal(m, b)
}
func (m *GwError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwError.Marshal(b, m, deterministic)
}
func (m *GwError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwError.Merge(m, src)
}
func (m *GwError) XXX_Size() int {
	return xxx_messageInfo_GwError.Size(m)
}
func (m *GwError) XXX_DiscardUnknown() {
	xxx_messageInfo_GwError.DiscardUnknown(m)
}

var xxx_messageInfo_GwError proto.InternalMessageInfo

func (m *GwError) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GwError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeat) Reset()         { *m = HeartBeat{} }
func (m *HeartBeat) String() string { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()    {}
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeat.Unmarshal(m, b)
}
func (m *HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeat.Marshal(b, m, deterministic)
}
func (m *HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeat.Merge(m, src)
}
func (m *HeartBeat) XXX_Size() int {
	return xxx_messageInfo_HeartBeat.Size(m)
}
func (m *HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeat proto.InternalMessageInfo

type Method1Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method1Request) Reset()         { *m = Method1Request{} }
func (m *Method1Request) String() string { return proto.CompactTextString(m) }
func (*Method1Request) ProtoMessage()    {}
func (*Method1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Method1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method1Request.Unmarshal(m, b)
}
func (m *Method1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method1Request.Marshal(b, m, deterministic)
}
func (m *Method1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method1Request.Merge(m, src)
}
func (m *Method1Request) XXX_Size() int {
	return xxx_messageInfo_Method1Request.Size(m)
}
func (m *Method1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Method1Request.DiscardUnknown(m)
}

var xxx_messageInfo_Method1Request proto.InternalMessageInfo

type Method1Reply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method1Reply) Reset()         { *m = Method1Reply{} }
func (m *Method1Reply) String() string { return proto.CompactTextString(m) }
func (*Method1Reply) ProtoMessage()    {}
func (*Method1Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *Method1Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method1Reply.Unmarshal(m, b)
}
func (m *Method1Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method1Reply.Marshal(b, m, deterministic)
}
func (m *Method1Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method1Reply.Merge(m, src)
}
func (m *Method1Reply) XXX_Size() int {
	return xxx_messageInfo_Method1Reply.Size(m)
}
func (m *Method1Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Method1Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Method1Reply proto.InternalMessageInfo

type Method2Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method2Request) Reset()         { *m = Method2Request{} }
func (m *Method2Request) String() string { return proto.CompactTextString(m) }
func (*Method2Request) ProtoMessage()    {}
func (*Method2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *Method2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method2Request.Unmarshal(m, b)
}
func (m *Method2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method2Request.Marshal(b, m, deterministic)
}
func (m *Method2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method2Request.Merge(m, src)
}
func (m *Method2Request) XXX_Size() int {
	return xxx_messageInfo_Method2Request.Size(m)
}
func (m *Method2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Method2Request.DiscardUnknown(m)
}

var xxx_messageInfo_Method2Request proto.InternalMessageInfo

type Method2Reply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method2Reply) Reset()         { *m = Method2Reply{} }
func (m *Method2Reply) String() string { return proto.CompactTextString(m) }
func (*Method2Reply) ProtoMessage()    {}
func (*Method2Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *Method2Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method2Reply.Unmarshal(m, b)
}
func (m *Method2Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method2Reply.Marshal(b, m, deterministic)
}
func (m *Method2Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method2Reply.Merge(m, src)
}
func (m *Method2Reply) XXX_Size() int {
	return xxx_messageInfo_Method2Reply.Size(m)
}
func (m *Method2Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Method2Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Method2Reply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GwError)(nil), "gwproto.GwError")
	proto.RegisterType((*HeartBeat)(nil), "gwproto.HeartBeat")
	proto.RegisterType((*Method1Request)(nil), "gwproto.Method1Request")
	proto.RegisterType((*Method1Reply)(nil), "gwproto.Method1Reply")
	proto.RegisterType((*Method2Request)(nil), "gwproto.Method2Request")
	proto.RegisterType((*Method2Reply)(nil), "gwproto.Method2Reply")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2f, 0x07, 0x33, 0x94, 0xcc, 0xb9, 0xd8, 0xdd,
	0xcb, 0x5d, 0x8b, 0x8a, 0xf2, 0x8b, 0x84, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x78, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4,
	0xf4, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x89, 0x9b, 0x8b, 0xd3, 0x23,
	0x35, 0xb1, 0xa8, 0xc4, 0x29, 0x35, 0xb1, 0x44, 0x49, 0x80, 0x8b, 0xcf, 0x37, 0xb5, 0x24, 0x23,
	0x3f, 0xc5, 0x30, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x89, 0x8f, 0x8b, 0x07, 0x2e, 0x52,
	0x90, 0x53, 0x89, 0x50, 0x61, 0x84, 0xa1, 0xc2, 0x08, 0xac, 0xc2, 0x49, 0x83, 0x4b, 0x30, 0x39,
	0x3f, 0x57, 0xaf, 0xaa, 0x30, 0x2f, 0xb5, 0x44, 0xcf, 0x3d, 0x1c, 0xec, 0x3c, 0x27, 0x76, 0x28,
	0x23, 0x80, 0x71, 0x11, 0x13, 0x8c, 0x9d, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x8c, 0x42, 0x63, 0x81, 0xd0, 0x00, 0x00, 0x00,
}
