// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tcpgate.proto

package gwProto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type GwError struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwError) Reset()         { *m = GwError{} }
func (m *GwError) String() string { return proto.CompactTextString(m) }
func (*GwError) ProtoMessage()    {}
func (*GwError) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{0}
}

func (m *GwError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwError.Unmarshal(m, b)
}
func (m *GwError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwError.Marshal(b, m, deterministic)
}
func (m *GwError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwError.Merge(m, src)
}
func (m *GwError) XXX_Size() int {
	return xxx_messageInfo_GwError.Size(m)
}
func (m *GwError) XXX_DiscardUnknown() {
	xxx_messageInfo_GwError.DiscardUnknown(m)
}

var xxx_messageInfo_GwError proto.InternalMessageInfo

func (m *GwError) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GwError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Method1Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method1Request) Reset()         { *m = Method1Request{} }
func (m *Method1Request) String() string { return proto.CompactTextString(m) }
func (*Method1Request) ProtoMessage()    {}
func (*Method1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{1}
}

func (m *Method1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method1Request.Unmarshal(m, b)
}
func (m *Method1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method1Request.Marshal(b, m, deterministic)
}
func (m *Method1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method1Request.Merge(m, src)
}
func (m *Method1Request) XXX_Size() int {
	return xxx_messageInfo_Method1Request.Size(m)
}
func (m *Method1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Method1Request.DiscardUnknown(m)
}

var xxx_messageInfo_Method1Request proto.InternalMessageInfo

type Method1Reply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method1Reply) Reset()         { *m = Method1Reply{} }
func (m *Method1Reply) String() string { return proto.CompactTextString(m) }
func (*Method1Reply) ProtoMessage()    {}
func (*Method1Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{2}
}

func (m *Method1Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method1Reply.Unmarshal(m, b)
}
func (m *Method1Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method1Reply.Marshal(b, m, deterministic)
}
func (m *Method1Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method1Reply.Merge(m, src)
}
func (m *Method1Reply) XXX_Size() int {
	return xxx_messageInfo_Method1Reply.Size(m)
}
func (m *Method1Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Method1Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Method1Reply proto.InternalMessageInfo

type Method2Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method2Request) Reset()         { *m = Method2Request{} }
func (m *Method2Request) String() string { return proto.CompactTextString(m) }
func (*Method2Request) ProtoMessage()    {}
func (*Method2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{3}
}

func (m *Method2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method2Request.Unmarshal(m, b)
}
func (m *Method2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method2Request.Marshal(b, m, deterministic)
}
func (m *Method2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method2Request.Merge(m, src)
}
func (m *Method2Request) XXX_Size() int {
	return xxx_messageInfo_Method2Request.Size(m)
}
func (m *Method2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Method2Request.DiscardUnknown(m)
}

var xxx_messageInfo_Method2Request proto.InternalMessageInfo

type Method2Reply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method2Reply) Reset()         { *m = Method2Reply{} }
func (m *Method2Reply) String() string { return proto.CompactTextString(m) }
func (*Method2Reply) ProtoMessage()    {}
func (*Method2Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d30d5155d328cc, []int{4}
}

func (m *Method2Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method2Reply.Unmarshal(m, b)
}
func (m *Method2Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method2Reply.Marshal(b, m, deterministic)
}
func (m *Method2Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method2Reply.Merge(m, src)
}
func (m *Method2Reply) XXX_Size() int {
	return xxx_messageInfo_Method2Reply.Size(m)
}
func (m *Method2Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Method2Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Method2Reply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GwError)(nil), "gwProto.GwError")
	proto.RegisterType((*Method1Request)(nil), "gwProto.Method1Request")
	proto.RegisterType((*Method1Reply)(nil), "gwProto.Method1Reply")
	proto.RegisterType((*Method2Request)(nil), "gwProto.Method2Request")
	proto.RegisterType((*Method2Reply)(nil), "gwProto.Method2Reply")
}

func init() { proto.RegisterFile("tcpgate.proto", fileDescriptor_83d30d5155d328cc) }

var fileDescriptor_83d30d5155d328cc = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x49, 0x2e, 0x48,
	0x4f, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2f, 0x0f, 0x00, 0x31,
	0xa4, 0x64, 0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2,
	0xf2, 0x4b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x8a, 0x21, 0xca, 0x94, 0xcc, 0xb9, 0xd8, 0xdd, 0xcb,
	0x5d, 0x8b, 0x8a, 0xf2, 0x8b, 0x84, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x78, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4,
	0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x49, 0x80, 0x8b, 0xcf, 0x37, 0xb5,
	0x24, 0x23, 0x3f, 0xc5, 0x30, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x89, 0x8f, 0x8b, 0x07,
	0x2e, 0x52, 0x90, 0x53, 0x89, 0x50, 0x61, 0x84, 0xa1, 0xc2, 0x08, 0xac, 0xc2, 0x68, 0x07, 0x23,
	0x17, 0x57, 0x48, 0x72, 0x81, 0x7b, 0x62, 0x49, 0x6a, 0x79, 0x62, 0xa5, 0x50, 0x08, 0x17, 0x3b,
	0xd4, 0x00, 0x21, 0x71, 0x3d, 0xa8, 0xf3, 0xf5, 0x50, 0x2d, 0x91, 0x12, 0xc5, 0x94, 0x00, 0xd9,
	0x25, 0xd9, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x61, 0x25, 0x3e, 0xfd, 0x32, 0x43, 0xfd, 0xf4, 0x72,
	0xfd, 0x5c, 0x88, 0xa4, 0x15, 0xa3, 0x16, 0xc2, 0x54, 0x23, 0x0c, 0x53, 0x8d, 0x70, 0x99, 0x6a,
	0x84, 0xcf, 0x54, 0x23, 0x2b, 0x46, 0x2d, 0x27, 0x0d, 0x2e, 0xc1, 0xe4, 0xfc, 0x5c, 0xbd, 0xaa,
	0xc2, 0xbc, 0xd4, 0x12, 0x3d, 0xf7, 0x70, 0x70, 0x60, 0x3a, 0xb1, 0x43, 0x19, 0x01, 0x8c, 0x8b,
	0x98, 0x60, 0xec, 0x24, 0x36, 0x30, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x49, 0x8b, 0x74,
	0xa4, 0xa0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TcpGatewayClient is the client API for TcpGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TcpGatewayClient interface {
	// 后端服务1
	// 注释
	// @transmit
	// @target backendsvr1 后端目标服务名
	// @upid 2 对应请求协议的id
	// @downid 3 对应响应协议的id
	Method1(ctx context.Context, in *Method1Request, opts ...grpc.CallOption) (*Method1Reply, error)
	// 后端服务2
	// 注释
	// @transmit
	// @target backendsvr2 后端目标服务名
	// @upid 4 对应请求协议的id
	// @downid 5 对应响应协议的id
	Method2(ctx context.Context, in *Method2Request, opts ...grpc.CallOption) (*Method2Reply, error)
}

type tcpGatewayClient struct {
	cc *grpc.ClientConn
}

func NewTcpGatewayClient(cc *grpc.ClientConn) TcpGatewayClient {
	return &tcpGatewayClient{cc}
}

func (c *tcpGatewayClient) Method1(ctx context.Context, in *Method1Request, opts ...grpc.CallOption) (*Method1Reply, error) {
	out := new(Method1Reply)
	err := c.cc.Invoke(ctx, "/gwProto.TcpGateway/Method1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tcpGatewayClient) Method2(ctx context.Context, in *Method2Request, opts ...grpc.CallOption) (*Method2Reply, error) {
	out := new(Method2Reply)
	err := c.cc.Invoke(ctx, "/gwProto.TcpGateway/Method2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TcpGatewayServer is the server API for TcpGateway service.
type TcpGatewayServer interface {
	// 后端服务1
	// 注释
	// @transmit
	// @target backendsvr1 后端目标服务名
	// @upid 2 对应请求协议的id
	// @downid 3 对应响应协议的id
	Method1(context.Context, *Method1Request) (*Method1Reply, error)
	// 后端服务2
	// 注释
	// @transmit
	// @target backendsvr2 后端目标服务名
	// @upid 4 对应请求协议的id
	// @downid 5 对应响应协议的id
	Method2(context.Context, *Method2Request) (*Method2Reply, error)
}

// UnimplementedTcpGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedTcpGatewayServer struct {
}

func (*UnimplementedTcpGatewayServer) Method1(ctx context.Context, req *Method1Request) (*Method1Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Method1 not implemented")
}
func (*UnimplementedTcpGatewayServer) Method2(ctx context.Context, req *Method2Request) (*Method2Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Method2 not implemented")
}

func RegisterTcpGatewayServer(s *grpc.Server, srv TcpGatewayServer) {
	s.RegisterService(&_TcpGateway_serviceDesc, srv)
}

func _TcpGateway_Method1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Method1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcpGatewayServer).Method1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwProto.TcpGateway/Method1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcpGatewayServer).Method1(ctx, req.(*Method1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TcpGateway_Method2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Method2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcpGatewayServer).Method2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwProto.TcpGateway/Method2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcpGatewayServer).Method2(ctx, req.(*Method2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _TcpGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gwProto.TcpGateway",
	HandlerType: (*TcpGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Method1",
			Handler:    _TcpGateway_Method1_Handler,
		},
		{
			MethodName: "Method2",
			Handler:    _TcpGateway_Method2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tcpgate.proto",
}
